### PR TITLE
Updated to Python 3.9

### PR DESCRIPTION
**Pull request by radarhere**
Minor suggestion for https://github.com/python-pillow/pillow-wheels/pull/169

### CODE REVIEW

**Comment by nulano** [comment]
I don't think it matters since it is only used by multibuild, but probably a good idea anyway, thank you.

**Comment by hugovk** [comment]
Does it make things slower?

For example, there could be dependencies without 3.9 wheels yet that need building from source.

**Comment by radarhere** [comment]
Looking at the Travis builds [before](https://travis-ci.com/github/python-pillow/pillow-wheels/builds/196970155) and [after](https://travis-ci.com/github/python-pillow/pillow-wheels/builds/199011361) - if anything, it was faster.

**Comment by nulano** [comment]
This is about GHA, not Travis (still needs to be enabled on the python-pillow repo). I looked at the latest run, and while it was a little bit slower, re-running the pre-PR run is now also slower by the same amount. Therefore I believe any difference is unrelated to this.

**Comment by hugovk** [comment]
👍

**Pull request merged**
